---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: data-prepper-cluster
  region: us-east-1

managedNodeGroups:
  - name: data-prepper-nodes
    instanceType: ["m5.large", "c3.large", "c4.large", "c5.large"]
    desiredCapacity: 3
    spot: true