---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: data-prepper-cluster
  region: us-east-1

managedNodeGroups:
  - name: data-prepper-nodes
    instanceTypes:  # âœ… Use PLURAL "instanceTypes" for array
      - m5.large
      - c5.large
      - c4.large
    desiredCapacity: 3
    minSize: 1
    maxSize: 6
    spot: true